version: '3.5'

services:
  lumen:
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    networks:
      - bitrix_my_network
    build: .
    command: php -S localhost:8000 -t public
    restart: always

networks:
  bitrix_my_network:
    driver: bridge
